
/Users/rav/.m2/repository/com/google/apis/google-api-services-cloudresourcemanager/v1beta1-rev10-1.21.0/google-api-services-cloudresourcemanager-v1beta1-rev10-1.21.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.7.2/hadoop-mapreduce-client-jobclient-2.7.2.jar
/Users/rav/.m2/repository/io/netty/netty-codec-http/4.1.3.Final/netty-codec-http-4.1.3.Final.jar
/Users/rav/.m2/repository/com/google/oauth-client/google-oauth-client-servlet/1.21.0/google-oauth-client-servlet-1.21.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-resourcemanager/0.6.0/google-cloud-resourcemanager-0.6.0.jar
/Users/rav/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
/Users/rav/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-core/0.6.0/google-cloud-core-0.6.0.jar
/Users/rav/.m2/repository/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar
/Users/rav/.m2/repository/org/scala-lang/scala-compiler/2.11.8/scala-compiler-2.11.8.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-speech/0.6.0/google-cloud-speech-0.6.0.jar
/Users/rav/.m2/repository/com/google/api-client/google-api-client-servlet/1.21.0/google-api-client-servlet-1.21.0.jar
/Users/rav/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/auth/google-auth-library-oauth2-http/0.6.0/google-auth-library-oauth2-http-0.6.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-bigquery/0.6.0/google-cloud-bigquery-0.6.0.jar
/Users/rav/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.1.0/protobuf-java-3.1.0.jar
/Users/rav/.m2/repository/io/grpc/grpc-auth/1.0.1/grpc-auth-1.0.1.jar
/Users/rav/.m2/repository/javax/transaction/transaction-api/1.1/transaction-api-1.1.jar
/Users/rav/.m2/repository/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar
/Users/rav/.m2/repository/com/google/inject/guice/4.0/guice-4.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/gax/0.0.22/gax-0.0.22.jar
/Users/rav/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.jar
/Users/rav/.m2/repository/io/netty/netty/3.8.0.Final/netty-3.8.0.Final.jar
/Users/rav/.m2/repository/io/grpc/grpc-core/1.0.1/grpc-core-1.0.1.jar
/Users/rav/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.13/jackson-xc-1.9.13.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-column/1.7.0/parquet-column-1.7.0.jar
/Users/rav/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-network-shuffle_2.11/2.0.2/spark-network-shuffle_2.11-2.0.2.jar
/Users/rav/.m2/repository/org/roaringbitmap/RoaringBitmap/0.5.11/RoaringBitmap-0.5.11.jar
/Users/rav/.m2/repository/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar
/Users/rav/.m2/repository/io/netty/netty-codec/4.1.3.Final/netty-codec-4.1.3.Final.jar
/Users/rav/.m2/repository/com/google/http-client/google-http-client/1.22.0/google-http-client-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-translate/0.6.0/google-cloud-translate-0.6.0.jar
/Users/rav/.m2/repository/org/antlr/antlr4-runtime/4.5.3/antlr4-runtime-4.5.3.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-tags_2.11/2.0.2/spark-tags_2.11-2.0.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar
/Users/rav/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
/Users/rav/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar
/Users/rav/.m2/repository/org/spark-project/hive/hive-exec/1.2.1.spark2/hive-exec-1.2.1.spark2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-core_2.11/2.0.2/spark-core_2.11-2.0.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-datastore/0.6.0/google-cloud-datastore-0.6.0.jar
/Users/rav/.m2/repository/io/netty/netty-transport/4.1.3.Final/netty-transport-4.1.3.Final.jar
/Users/rav/.m2/repository/org/json4s/json4s-core_2.11/3.2.11/json4s-core_2.11-3.2.11.jar
/Users/rav/.m2/repository/io/grpc/grpc-context/1.0.1/grpc-context-1.0.1.jar
/Users/rav/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar
/Users/rav/.m2/repository/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar
/Users/rav/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar
/Users/rav/.m2/repository/io/netty/netty-common/4.1.3.Final/netty-common-4.1.3.Final.jar
/Users/rav/.m2/repository/org/json4s/json4s-jackson_2.11/3.2.11/json4s-jackson_2.11-3.2.11.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-client/2.7.2/hadoop-yarn-client-2.7.2.jar
/Users/rav/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
/Users/rav/.m2/repository/com/squareup/okio/okio/1.6.0/okio-1.6.0.jar
/Users/rav/.m2/repository/com/google/code/gson/gson/2.3/gson-2.3.jar
/Users/rav/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/2.0.2/spark-sql_2.11-2.0.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-cloud-language-v1beta1/0.1.0/grpc-google-cloud-language-v1beta1-0.1.0.jar
/Users/rav/.m2/repository/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar
/Users/rav/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar
/Users/rav/.m2/repository/com/twitter/parquet-hadoop-bundle/1.6.0/parquet-hadoop-bundle-1.6.0.jar
/Users/rav/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-hdfs/2.7.2/hadoop-hdfs-2.7.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-app/2.7.2/hadoop-mapreduce-client-app-2.7.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-launcher_2.11/2.0.2/spark-launcher_2.11-2.0.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/spotify/scio-core_2.11/0.2.6/scio-core_2.11-0.2.6.jar
/Users/rav/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar
/Users/rav/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar
/Users/rav/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
/Users/rav/.m2/repository/org/apache/mesos/mesos/0.21.1/mesos-0.21.1-shaded-protobuf.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-catalyst_2.11/2.0.2/spark-catalyst_2.11-2.0.2.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-format/2.3.0-incubating/parquet-format-2.3.0-incubating.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.8.3/jackson-core-2.8.3.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-devtools-cloudtrace-v1/0.1.0/grpc-google-devtools-cloudtrace-v1-0.1.0.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-generator/1.7.0/parquet-generator-1.7.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-common/2.7.2/hadoop-yarn-server-common-2.7.2.jar
/Users/rav/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.jar
/Users/rav/.m2/repository/io/grpc/grpc-stub/1.0.1/grpc-stub-1.0.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/twitter/chill-protobuf/0.8.1/chill-protobuf-0.8.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.8.3/jackson-module-paranamer-2.8.3.jar
/Users/rav/.m2/repository/com/google/api-client/google-api-client-java6/1.22.0/google-api-client-java6-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-pubsub/0.6.0/google-cloud-pubsub-0.6.0.jar
/Users/rav/.m2/repository/com/googlecode/javaewah/JavaEWAH/0.6.6/JavaEWAH-0.6.6.jar
/Users/rav/.m2/repository/org/glassfish/hk2/hk2-api/2.4.0-b34/hk2-api-2.4.0-b34.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/2.7.2/hadoop-client-2.7.2.jar
/Users/rav/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-logging/0.6.0/google-cloud-logging-0.6.0.jar
/Users/rav/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.4.0-b34/aopalliance-repackaged-2.4.0-b34.jar
/Users/rav/.m2/repository/io/grpc/grpc-protobuf/1.0.1/grpc-protobuf-1.0.1.jar
/Users/rav/.m2/repository/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar
/Users/rav/.m2/repository/com/google/http-client/google-http-client-appengine/1.21.0/google-http-client-appengine-1.21.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-yarn_2.11/2.0.2/spark-yarn_2.11-2.0.2.jar
/Users/rav/.m2/repository/com/google/auto/auto-common/0.3/auto-common-0.3.jar
/Users/rav/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.2/metrics-json-3.1.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-compute/0.6.0/google-cloud-compute-0.6.0.jar
/Users/rav/.m2/repository/com/google/oauth-client/google-oauth-client/1.22.0/google-oauth-client-1.22.0.jar
/Users/rav/.m2/repository/com/univocity/univocity-parsers/2.1.1/univocity-parsers-2.1.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-monitoring/0.6.0/google-cloud-monitoring-0.6.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-cloud-vision-v1/0.1.0/grpc-google-cloud-vision-v1-0.1.0.jar
/Users/rav/.m2/repository/net/java/dev/jets3t/jets3t/0.7.1/jets3t-0.7.1.jar
/Users/rav/.m2/repository/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
/Users/rav/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar
/Users/rav/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar
/Users/rav/.m2/repository/com/google/api/grpc/grpc-google-pubsub-v1/0.1.0/grpc-google-pubsub-v1-0.1.0.jar
/Users/rav/.m2/repository/org/apache/hadoop/hadoop-common/2.7.2/hadoop-common-2.7.2.jar
/Users/rav/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar
/Users/rav/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar
/Users/rav/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-sketch_2.11/2.0.2/spark-sketch_2.11-2.0.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-unsafe_2.11/2.0.2/spark-unsafe_2.11-2.0.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcsio/1.5.4/gcsio-1.5.4.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-clouddebugger/v2-rev8-1.22.0/google-api-services-clouddebugger-v2-rev8-1.22.0.jar
/Users/rav/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/1.1.33.Fork19/netty-tcnative-boringssl-static-1.1.33.Fork19.jar
/Users/rav/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar
/Users/rav/.m2/repository/org/apache/avro/avro-ipc/1.7.7/avro-ipc-1.7.7.jar
/Users/rav/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar
/Users/rav/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
/Users/rav/.m2/repository/io/grpc/grpc-all/1.0.1/grpc-all-1.0.1.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-hadoop/1.7.0/parquet-hadoop-1.7.0.jar
/Users/rav/.m2/repository/io/netty/netty-resolver/4.1.3.Final/netty-resolver-4.1.3.Final.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-trace/0.6.0/google-cloud-trace-0.6.0.jar
/Users/rav/.m2/repository/io/grpc/grpc-protobuf-nano/1.0.1/grpc-protobuf-nano-1.0.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/twitter/chill_2.11/0.8.1/chill_2.11-0.8.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/bigdataoss/util/1.5.4/util-1.5.4.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-translate/v2-rev47-1.22.0/google-api-services-translate-v2-rev47-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.8.3/jackson-databind-2.8.3.jar
/Users/rav/.m2/repository/org/apache/avro/avro-mapred/1.7.7/avro-mapred-1.7.7-hadoop2.jar
/Users/rav/.m2/repository/com/google/api/grpc/grpc-pubsub-v1/0.0.2/grpc-pubsub-v1-0.0.2.jar
/Users/rav/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar
/Users/rav/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
/Users/rav/.m2/repository/org/scala-lang/scalap/2.11.8/scalap-2.11.8.jar
/Users/rav/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar
/Users/rav/.m2/repository/org/apache/xbean/xbean-asm5-shaded/4.4/xbean-asm5-shaded-4.4.jar
/Users/rav/.m2/repository/io/netty/netty-all/4.0.29.Final/netty-all-4.0.29.Final.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-cloud-speech-v1beta1/0.1.0/grpc-google-cloud-speech-v1beta1-0.1.0.jar
/Users/rav/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-encoding/1.7.0/parquet-encoding-1.7.0.jar
/Users/rav/.m2/repository/net/sf/py4j/py4j/0.10.3/py4j-0.10.3.jar
/Users/rav/.m2/repository/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar
/Users/rav/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.2/metrics-jvm-3.1.2.jar
/Users/rav/.m2/repository/io/grpc/grpc-okhttp/1.0.1/grpc-okhttp-1.0.1.jar
/Users/rav/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/spotify/scio-bigquery_2.11/0.2.6/scio-bigquery_2.11-0.2.6.jar
/Users/rav/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar
/Users/rav/.m2/repository/org/spark-project/hive/hive-metastore/1.2.1.spark2/hive-metastore-1.2.1.spark2.jar
/Users/rav/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.2/hadoop-annotations-2.7.2.jar
/Users/rav/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar
/Users/rav/.m2/repository/com/google/api/grpc/grpc-core-proto/0.0.3/grpc-core-proto-0.0.3.jar
/Users/rav/.m2/repository/com/google/api/grpc/grpc-google-iam-v1/0.1.0/grpc-google-iam-v1-0.1.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/me/lyh/protobuf-generic_2.11/0.1.0/protobuf-generic_2.11-0.1.0.jar
/Users/rav/.m2/repository/org/codehaus/janino/commons-compiler/2.7.8/commons-compiler-2.7.8.jar
/Users/rav/.m2/repository/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar
/Users/rav/.m2/repository/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.jar
/Users/rav/.m2/repository/com/google/http-client/google-http-client-jackson2/1.22.0/google-http-client-jackson2-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/1.5.4-hadoop2/gcs-connector-1.5.4-hadoop2.jar
/Users/rav/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar
/Users/rav/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.2/metrics-graphite-3.1.2.jar
/Users/rav/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar
/Users/rav/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
/Users/rav/.m2/repository/org/apache/avro/avro/1.7.7/avro-1.7.7.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-devtools-clouderrorreporting-v1beta1/0.1.0/grpc-google-devtools-clouderrorreporting-v1beta1-0.1.0.jar
/Users/rav/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/spark/spark-network-common_2.11/2.0.2/spark-network-common_2.11-2.0.2.jar
/Users/rav/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar
/Users/rav/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/apis/google-api-services-dataproc/v1-rev9-1.22.0/google-api-services-dataproc-v1-rev9-1.22.0.jar
/Users/rav/.m2/repository/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.jar
/Users/rav/.m2/repository/org/codehaus/janino/janino/2.7.8/janino-2.7.8.jar
/Users/rav/.m2/repository/io/netty/netty-buffer/4.1.3.Final/netty-buffer-4.1.3.Final.jar
/Users/rav/.m2/repository/org/mortbay/jetty/servlet-api/2.5-20081211/servlet-api-2.5-20081211.jar
/Users/rav/.m2/repository/org/apache/hadoop/hadoop-yarn-server-web-proxy/2.2.0/hadoop-yarn-server-web-proxy-2.2.0.jar
/Users/rav/.m2/repository/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
/Users/rav/.m2/repository/org/glassfish/hk2/hk2-utils/2.4.0-b34/hk2-utils-2.4.0-b34.jar
/Users/rav/.m2/repository/joda-time/joda-time/2.9.2/joda-time-2.9.2.jar
/Users/rav/.m2/repository/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar
/Users/rav/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-common/2.7.2/hadoop-mapreduce-client-common-2.7.2.jar
/Users/rav/.m2/repository/com/google/cloud/bigtable/bigtable-protos/0.3.0/bigtable-protos-0.3.0.jar
/Users/rav/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-logging-v2/0.1.1/grpc-google-logging-v2-0.1.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/apis/google-api-services-storage/v1-rev85-1.22.0/google-api-services-storage-v1-rev85-1.22.0.jar
/Users/rav/.m2/repository/org/joda/joda-convert/1.8.1/joda-convert-1.8.1.jar
/Users/rav/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar
/Users/rav/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar
/Users/rav/.m2/repository/com/twitter/algebird-core_2.11/0.12.2/algebird-core_2.11-0.12.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-monitoring-v3/0.1.0/grpc-google-monitoring-v3-0.1.0.jar
/Users/rav/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.13/jackson-jaxrs-1.9.13.jar
/Users/rav/.m2/repository/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-storage/0.6.0/google-cloud-storage-0.6.0.jar
/Users/rav/.m2/repository/com/google/api-client/google-api-client-appengine/1.21.0/google-api-client-appengine-1.21.0.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-pubsub/v1-rev10-1.22.0/google-api-services-pubsub-v1-rev10-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud/0.6.0/google-cloud-0.6.0.jar
/Users/rav/.m2/repository/org/json/json/20151123/json-20151123.jar
/Users/rav/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
/Users/rav/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar
/Users/rav/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/dataflow/google-cloud-dataflow-java-sdk-all/1.8.0/google-cloud-dataflow-java-sdk-all-1.8.0.jar
/Users/rav/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar
/Users/rav/.m2/repository/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar
/Users/rav/.m2/repository/io/grpc/grpc-netty/1.0.1/grpc-netty-1.0.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/datastore/datastore-v1-proto-client/1.3.0/datastore-v1-proto-client-1.3.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/auth/google-auth-library-credentials/0.6.0/google-auth-library-credentials-0.6.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-common/2.7.2/hadoop-yarn-common-2.7.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/spotify/scio-hdfs_2.11/0.2.6/scio-hdfs_2.11-0.2.6.jar
/Users/rav/.m2/repository/com/google/http-client/google-http-client-jackson/1.22.0/google-http-client-jackson-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-shuffle/2.7.2/hadoop-mapreduce-client-shuffle-2.7.2.jar
/Users/rav/.m2/repository/org/apache/avro/avro-ipc/1.7.7/avro-ipc-1.7.7-tests.jar
/Users/rav/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-vision/0.6.0/google-cloud-vision-0.6.0.jar
/Users/rav/.m2/repository/org/glassfish/hk2/hk2-locator/2.4.0-b34/hk2-locator-2.4.0-b34.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/bigdataoss/util-hadoop/1.5.4-hadoop2/util-hadoop-1.5.4-hadoop2.jar
/Users/rav/.m2/repository/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.jar
/Users/rav/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
/Users/rav/.m2/repository/com/google/protobuf/protobuf-java-util/3.0.0/protobuf-java-util-3.0.0.jar
/Users/rav/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.2/hadoop-auth-2.7.2.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-dns/v1-rev7-1.21.0/google-api-services-dns-v1-rev7-1.21.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.8.3/jackson-annotations-2.8.3.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-errorreporting/0.6.0/google-cloud-errorreporting-0.6.0.jar
/Users/rav/.m2/repository/com/google/protobuf/nano/protobuf-javanano/3.0.0-alpha-5/protobuf-javanano-3.0.0-alpha-5.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-api/2.7.2/hadoop-yarn-api-2.7.2.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-dataflow/v1b3-rev36-1.22.0/google-api-services-dataflow-v1b3-rev36-1.22.0.jar
/Users/rav/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-datastore-protobuf/v1beta2-rev1-4.0.0/google-api-services-datastore-protobuf-v1beta2-rev1-4.0.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-codec-http2/4.1.3.Final/netty-codec-http2-4.1.3.Final.jar
/Users/rav/.m2/repository/io/grpc/grpc-protobuf-lite/1.0.1/grpc-protobuf-lite-1.0.1.jar
/Users/rav/.m2/repository/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar
/Users/rav/.m2/repository/com/google/oauth-client/google-oauth-client-appengine/1.21.0/google-oauth-client-appengine-1.21.0.jar
/Users/rav/.m2/repository/com/google/http-client/google-http-client-protobuf/1.22.0/google-http-client-protobuf-1.22.0.jar
/Users/rav/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar
/Users/rav/.m2/repository/com/google/oauth-client/google-oauth-client-java6/1.22.0/google-oauth-client-java6-1.22.0.jar
/Users/rav/.m2/repository/net/razorvine/pyrolite/4.13/pyrolite-4.13.jar
/Users/rav/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/datastore/datastore-v1-protos/1.3.0/datastore-v1-protos-1.3.0.jar
/Users/rav/.m2/repository/com/esotericsoftware/minlog/1.3.0/minlog-1.3.0.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-compute/v1-rev103-1.21.0/google-api-services-compute-v1-rev103-1.21.0.jar
/Users/rav/.m2/repository/com/google/auto/service/auto-service/1.0-rc2/auto-service-1.0-rc2.jar
/Users/rav/.m2/repository/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar
/Users/rav/.m2/repository/com/google/api-client/google-api-client/1.22.0/google-api-client-1.22.0.jar
/Users/rav/.m2/repository/com/google/guava/guava-jdk5/17.0/guava-jdk5-17.0.jar
/Users/rav/.m2/repository/com/google/apis/google-api-services-bigquery/v2-rev317-1.22.0/google-api-services-bigquery-v2-rev317-1.22.0.jar
/Users/rav/.m2/repository/com/google/http-client/google-http-client-jdo/1.21.0/google-http-client-jdo-1.21.0.jar
/Users/rav/.m2/repository/com/squareup/okhttp/okhttp/2.5.0/okhttp-2.5.0.jar
/Users/rav/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar
/Users/rav/.m2/repository/javax/jdo/jdo2-api/2.3-eb/jdo2-api-2.3-eb.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-dns/0.6.0/google-cloud-dns-0.6.0.jar
/Users/rav/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar
/Users/rav/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar
/Users/rav/.m2/repository/org/json4s/json4s-ast_2.11/3.2.11/json4s-ast_2.11-3.2.11.jar
/Users/rav/.m2/repository/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar
/Users/rav/.m2/repository/org/xerial/snappy/snappy-java/1.1.2.6/snappy-java-1.1.2.6.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-common/1.7.0/parquet-common-1.7.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/alibaba/dns-cache-manipulator/1.5.1/dns-cache-manipulator-1.5.1.jar
/Users/rav/.m2/repository/com/google/api-client/google-api-client-jackson2/1.22.0/google-api-client-jackson2-1.22.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/auto/value/auto-value/1.2/auto-value-1.2.jar
/Users/rav/.m2/repository/org/apache/velocity/velocity/1.7/velocity-1.7.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.2/hadoop-mapreduce-client-core-2.7.2.jar
/Users/rav/.m2/repository/org/apache/parquet/parquet-jackson/1.7.0/parquet-jackson-1.7.0.jar
/Users/rav/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
/Users/rav/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/cloud/google-cloud-language/0.6.0/google-cloud-language-0.6.0.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.11/2.8.3/jackson-module-scala_2.11-2.8.3.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-server-nodemanager/2.7.2/hadoop-yarn-server-nodemanager-2.7.2.jar
/Users/rav/.m2/repository/com/esotericsoftware/kryo-shaded/3.0.3/kryo-shaded-3.0.3.jar
/Users/rav/.m2/repository/net/jpountz/lz4/lz4/1.3.0/lz4-1.3.0.jar
/Users/rav/.m2/repository/commons-fileupload/commons-fileupload/1.3.1/commons-fileupload-1.3.1.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/twitter/chill-java/0.8.1/chill-java-0.8.1.jar
/Users/rav/.m2/repository/io/netty/netty-handler/4.1.3.Final/netty-handler-4.1.3.Final.jar
/Users/rav/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar
/Users/rav/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/api/grpc/grpc-google-common-protos/0.1.1/grpc-google-common-protos-0.1.1.jar
/Users/rav/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar
/Users/rav/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar
/Users/rav/.m2/repository/asm/asm/3.1/asm-3.1.jar
/Users/rav/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar
