addSbtPlugin("com.eed3si9n"       % "sbt-assembly"           % "0.14.3")
addSbtPlugin("org.xerial.sbt"     % "sbt-pack"               % "0.8.0")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                % "1.0.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"            % "1.0.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"          % "1.4.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"           % "1.1")
addSbtPlugin("org.scalastyle"     % "scalastyle-sbt-plugin"  % "0.8.0")
